### ISSUE TITLE
USER STORY: Home Page

### ISSUE THREAD

**Issue by tanisecarvalho** [tanisecarvalho/i-was-there#1]
EPIC: Home Page

As a **site user** I can **visit the website home page** so that **I can understand what this website is about**.

**Acceptance Criteria**

- [x] The home page has a menu to log in and signup
- [ ] It has the logo and a big hero image describing the business
- [ ] It has an about us section to instruct the users on how to use it
- [ ] It has the latest three concerts added to the platform
- [ ] It has a connect with us section with social network links

**Tasks**

- [x] Design and create a home page
- [ ] Connect to the database to get the last three concerts
- [x] Test functionality

**Comment by tanisecarvalho** [comment]
Changes in acceptance criteria were made and the home page just includes the logo, text description and links to login, logout.
