### ISSUE TITLE
USER STORY: Login

### ISSUE THREAD

**Issue by tanisecarvalho** [tanisecarvalho/i-was-there#10]
EPIC: Account

As a **site user** I can **login to my account** so that **I can have full access to my information**.

**Acceptance Criteria**

- [x] Login form has username and password
- [x] After submitting the form the user is redirected to the home page where they can see all concerts

**Tasks**

- [x] Create and implement login page
- [x] Add form validation and error handling
- [x] Test functionality

**Comment by tanisecarvalho** [comment]
Allauth added and page created and layout applied.
