### ISSUE TITLE
USER STORY: Logout

### ISSUE THREAD

**Issue by tanisecarvalho** [tanisecarvalho/i-was-there#11]
EPIC: Account

As a **site user** I can **log out of my account** so that **I can keep my account disconnected while not in use**.

**Acceptance Criteria**

- [x] Logout page asks the user to confirm if they want to leave.
- [x] After submitting the form the user is redirected to the home page of the website

**Tasks**

- [x] Create and implement logout page
- [x] Add form validation and error handling
- [x] Test functionality

**Comment by tanisecarvalho** [comment]
Allauth added and page created and layout applied.
