### ISSUE TITLE
USER STORY: Edit Account

### ISSUE THREAD

**Issue by tanisecarvalho** [tanisecarvalho/i-was-there#14]
EPIC: Account

As a **site user** I can **edit my account** so that **I can upload new information to it**.

**Acceptance Criteria**

- [ ] My profile has a username, password, name, country, favourite band, and profile picture
- [ ] I can edit the fields on my account to add extra information after signing up

**Tasks**

- [ ] Create and implement profile page
- [ ] Add form validation and error handling
- [ ] Test functionality

**Comment by tanisecarvalho** [comment]
Not implemented on Sprint 3, as changes/visualisation of profile might not be added to the MVP.
