### ISSUE TITLE
USER STORY: Admin Panel Concerts

### ISSUE THREAD

**Issue by tanisecarvalho** [tanisecarvalho/i-was-there#15]
EPIC: Admin

As a **site admin** I can **see all the concerts created** so that **I can make changes when needed**.

**Acceptance Criteria**

- [x] Admin can create, read, update and delete concerts
- [x] When a concert is deleted all users that have it to their list, won't have it anymore

**Tasks**

- [x] Create superuser 
- [x] Add concert to admin panel

**Comment by tanisecarvalho** [comment]
Installed summernote library
