### ISSUE TITLE
USER STORY: Add a New Concert

### ISSUE THREAD

**Issue by tanisecarvalho** [tanisecarvalho/i-was-there#2]
EPIC: Concert

As a **site user** I can **create a concert** so that **add it to my list and share it with other users**.

**Acceptance Criteria**

- [x] Concert form has band, date, country, and city, describe the concert in one sentence, upload a picture
- [x] After submitting the form the user is redirected to the View Concert page

**Tasks**

- [x] Implement and design new concert item
- [x] Implement and design concert comments item

**Comment by tanisecarvalho** [comment]
Created models for Band, Concert and Comment.

**Comment by tanisecarvalho** [comment]
Page add-concert.html created and CREATE working.
