### ISSUE TITLE
USER STORY: Base Layout

### ISSUE THREAD

**Issue by tanisecarvalho** [tanisecarvalho/i-was-there#27]
EPIC: Base Setup

As a **developer** I need to **create the base layout page** so that **all other pages can use the same layout**.

**Acceptance Criteria**

- [x] It must have a footer
- [x] It must have a nav bar
- [x] It must be developed according to the colour palette and fonts decided for the site

**Tasks**

- [x] Create page base.html

**Comment by tanisecarvalho** [comment]
Base layout created. Different menu on the nav bar will be included later with authentication.
