### ISSUE TITLE
USER STORY: NavBar Menu

### ISSUE THREAD

**Issue by tanisecarvalho** [tanisecarvalho/i-was-there#28]
EPIC: Base Setup

As a **developer** I need to **create the navbar menu** so that **the users can navigate on the website**.

**Acceptance Criteria**

- [x] It must be developed according to the colour palette and fonts decided for the site
- [x] It must have different items depending if the user is logged in or not.

**Tasks**

- [x] Create the navbar
- [x] Add permissions for authenticated users

**Comment by tanisecarvalho** [comment]
Navbar created according to the acceptance criteria.
