### ISSUE TITLE
USER STORY: Footer

### ISSUE THREAD

**Issue by tanisecarvalho** [tanisecarvalho/i-was-there#29]
EPIC: Base Setup

As a **developer** I need to **create a footer** so that **all other pages can use the same footer**.

**Acceptance Criteria**

- [x] It must be developed according to the colour palette and fonts decided for the site
- [x] It must have the website name
- [x] It must have the developer's name and social links
- [x] It must inform this is a project for education purposes

**Tasks**

- [ ] Create footer.html

**Comment by tanisecarvalho** [comment]
Footer developed according to the acceptance criteria
