### ISSUE TITLE
USER STORY: Add to my List

### ISSUE THREAD

**Issue by tanisecarvalho** [tanisecarvalho/i-was-there#3]
EPIC: Concert

As a **site user** I can **add a concert created by other users** so that **I have it on my list**.

**Acceptance Criteria**

- [x] Add to my list form has describe the concert in one sentence, upload a picture
- [x] After submitting the form the user is redirected to the View Concert page

**Tasks**

- [x] Create add to my list page
- [x] Test functionality

**Comment by tanisecarvalho** [comment]
Page add_to_my_list.html created. Concerts are added to the user and they can add comment and picture. Redirectioned to view concert page after.
