### ISSUE TITLE
USER STORY: Static Files

### ISSUE THREAD

**Issue by tanisecarvalho** [tanisecarvalho/i-was-there#30]
EPIC: Base Setup

As a **developer** I need to **create static files and their folders** so that **all media, CSS and javascript scripts will work**.

**Acceptance Criteria**

- [ ] The files must be host on cloudinary

**Tasks**

- [x] Create static folders
- [x] Create static files
- [ ] Host on cloudinary

**Comment by tanisecarvalho** [comment]
Issues with hosting the static files to Cloudinary, led this user story to be changed and all the static files where created and hosted using whitenoise.
