### ISSUE TITLE
USER STORY: My Concerts

### ISSUE THREAD

**Issue by tanisecarvalho** [tanisecarvalho/i-was-there#31]
EPIC: Concerts

As a **user** I can **see all concerts that I have added to my list** so that **I can see all the concerts I have been to**.

**Acceptance Criteria**

- [x] My concerts page must have cards with each concert that the user has been to and a search bar by band and country
- [x] The card has: band name, date, location, how many users added the concert to their lists, and a button to delete the concert from the user list

**Tasks**

- [x] Create and implement my concerts page
- [x] Add search functionality
- [x] Add pagination
- [x] Test functionality

**Comment by tanisecarvalho** [comment]
Page and model created. Only showing concerts that are on the user list.
