### ISSUE TITLE
USER STORY: Edit Concert

### ISSUE THREAD

**Issue by tanisecarvalho** [tanisecarvalho/i-was-there#4]
EPIC: Concert

As a **site user** I can **edit a concert that I created** so that **I can change misinformation**.

**Acceptance Criteria**

- [x] Edit Concert form has band, date, country, city, describe the concert in one sentence, upload a picture
- [x] After submitting the form the user is redirected to the View Concert page
- [x] The user can't edit a concert without being logged in
- [x] The user can't edit a concert they didn't create

**Tasks**

- [x] Create edit concert page
- [x] Test functionality

**Comment by tanisecarvalho** [comment]
Edit concert feature created. Validation will be done on the next sprint on validation user story.
