### ISSUE TITLE
USER STORY: Delete Concert

### ISSUE THREAD

**Issue by tanisecarvalho** [tanisecarvalho/i-was-there#5]
EPIC: Concert

As a **site user** I can **delete a concert** so that **I can remove it from my list**.

**Acceptance Criteria**

- [x] Delete a concert page shows a preview of the concert and asks the user to confirm they want to delete it
- [x] If other users have added the concert to their list, the ownership of the concert goes to the admin
- [x] The concert is removed from the user list
- [x] After the confirmation the user is redirected to my concerts page

**Tasks**

- [x] Create delete concert page
- [x] Test functionality

**Comment by tanisecarvalho** [comment]
Edit concert feature created. Validation will be done in the next sprint on the validation user story. Needs to check if there are other users who added the concert.

**Comment by tanisecarvalho** [comment]
User story will be moved to the next sprint to include permission to delete and transfer ownership to admin.
