### ISSUE TITLE
USER STORY: View Concert

### ISSUE THREAD

**Issue by tanisecarvalho** [tanisecarvalho/i-was-there#6]
EPIC: Concert

As a **site user** I can **view a concert** so that **I can check all the comments and gallery**.

**Acceptance Criteria**

- [x] The view concert page has an overview of the concert with the band name, date, location, and how many users added the concert to their lists
- [x] It has the comments of all users who added it to their lists
- [x] It has a gallery with pictures that users have uploaded

**Tasks**

- [x] Create view concert page
- [x] Add carousel for gallery
- [x] Test functionality

**Comment by tanisecarvalho** [comment]
Page view_concert.html added. Gallery for pictures and cards for the comments.
