### ISSUE TITLE
USER STORY: Concerts Home Page

### ISSUE THREAD

**Issue by tanisecarvalho** [tanisecarvalho/i-was-there#8]
EPIC: Concerts

As a **site user** I can **see all concerts created on the site** so that **I can add the ones I want to my list**.

**Acceptance Criteria**

- [x] After the login, the home page must have cards with each concert and a search bar by band and country
- [x] The card has: band name, date, location, how many users added the concert to their lists, and a button to add to my list in case the user hasn't it already

**Tasks**

- [x] Create and implement home page
- [x] Add search functionality
- [x] Add pagination
- [x] Test functionality

**Comment by tanisecarvalho** [comment]
The page was created with a model and template. 
The colour palette, typography and logo are defined.

**Comment by tanisecarvalho** [comment]
Navbar with search added

**Comment by tanisecarvalho** [comment]
Add search functionality by band and/or country.
