### ISSUE TITLE
USER STORY: Create an Account

### ISSUE THREAD

**Issue by tanisecarvalho** [tanisecarvalho/i-was-there#9]
EPIC: Account

As a **site user** I can **create an account** so that **can have access to the concerts and add my own**.

**Acceptance Criteria**

- [x] Sign up form has username, password and confirm password
- [x] After submitting the form the user is redirected to the home page where they can see all concerts

**Tasks**

- [x] Create and implement a signup page
- [x] Add form validation and error handling
- [x] Test functionality

**Comment by tanisecarvalho** [comment]
Allauth added and page created and layout applied.
